### ISSUE TITLE
The running time is too long

### ISSUE THREAD

**Issue by queey1** [stanford-iprl-lab/ao-grasp#6]
Thank you for your excellent work！I am running the script 'python contact_graspnet/contact_graspnet/run_cgn_on_heatmap_file.py' on a Nvidia 3090 GPU, but it takes ten minutes to complete. Is that normal?

**Comment by ClaireLC** [comment]
The first time you run CGN, loading their model can sometimes take quite a few minutes. But, in my experience, after the first time, the script should be faster.

**Comment by queey1** [comment]
It seems to be a problem with the TensorFlow-gpu 2.2 version, which is too old for the 30 series graphics cards. I am trying to update the version to 2.5.0.
