### ISSUE TITLE
About dataset release

### ISSUE THREAD

**Issue by SshiJwu** [stanford-iprl-lab/ao-grasp#9]
Hello, thank you for such wonderful work. I would like to ask when the dataset will be open-sourced, and could you send me a copy first?

**Comment by ClaireLC** [comment]
Thank you for your interest in AO-Grasp. We hope to be able to release the dataset at the end of this month. Until then, we are unable to share the dataset prior to the open-source release.

**Comment by SshiJwu** [comment]
any update?

**Comment by ClaireLC** [comment]
Yes, we are pleased to say that we are now ready to release the AO-Grasp dataset. Please see the readme [here](https://github.com/stanford-iprl-lab/ao-grasp/tree/main/aograsp_dataset_utils) for all the details.

**Comment by SshiJwu** [comment]
Thanks for your reply.
